### PR TITLE
Load as module instead of as hapi plugin.  Now with lab tests!

### PR DESCRIPTION
**Pull request by orthagonal**

### CODE REVIEW

**Comment by orthagonal** [comment]
needs review and merge from @jgallen23

**Comment by jgallen23** [comment]
The issue was to add support for loading as a module, not to remove the hapi plugin functionality

**Comment by orthagonal** [comment]
should support both module and register modes
includes test for both

**Comment by jgallen23** [comment]
@orthagonal when you have a chance, can you go through and fix all the linting errors?

**Pull request closed without merging**
